#!/usr/bin/env node

/**
 * Langfuse Trace Analysis Agent
 * Queries Langfuse, analyzes patterns, generates lessons learned
 */

const LANGFUSE_PUBLIC_KEY = process.env.LANGFUSE_PUBLIC_KEY;
const LANGFUSE_SECRET_KEY = process.env.LANGFUSE_SECRET_KEY;
const LANGFUSE_BASE_URL = process.env.LANGFUSE_BASE_URL || 'https://us.cloud.langfuse.com';

async function fetchTraces() {
  // Query Langfuse API for past week
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
  
  const response = await fetch(`${LANGFUSE_BASE_URL}/api/public/traces?fromTimestamp=${oneWeekAgo}`, {
    headers: {
      'Authorization': 'Basic ' + Buffer.from(`${LANGFUSE_PUBLIC_KEY}:${LANGFUSE_SECRET_KEY}`).toString('base64')
    }
  });

  if (!response.ok) {
    throw new Error(`Langfuse API error: ${response.status}`);
  }

  return response.json();
}

async function analyzeTraces(traces) {
  const analysis = {
    total: traces.length,
    byAgent: {},
    successful: [],
    failed: [],
    highLatency: [],
    insights: []
  };

  for (const trace of traces) {
    const agentId = trace.userId || trace.metadata?.agentId || 'unknown';
    
    // Count by agent
    analysis.byAgent[agentId] = (analysis.byAgent[agentId] || 0) + 1;

    // Track success/failure
    if (trace.metadata?.success === false || trace.level === 'ERROR') {
      analysis.failed.push(trace);
    } else {
      analysis.successful.push(trace);
    }

    // Track high latency (>10s)
    if (trace.metadata?.latencyMs > 10000) {
      analysis.highLatency.push({
        agent: agentId,
        latency: trace.metadata.latencyMs,
        traceId: trace.id
      });
    }
  }

  // Generate insights
  const successRate = (analysis.successful.length / analysis.total * 100).toFixed(1);
  analysis.insights.push(`Overall success rate: ${successRate}%`);

  // Top/bottom performers
  const agentStats = Object.entries(analysis.byAgent)
    .map(([agent, count]) => ({ agent, count }))
    .sort((a, b) => b.count - a.count);
  
  if (agentStats.length > 0) {
    analysis.insights.push(`Most active agent: ${agentStats[0].agent} (${agentStats[0].count} traces)`);
  }

  if (analysis.highLatency.length > 0) {
    const avgLatency = (analysis.highLatency.reduce((sum, t) => sum + t.latency, 0) / analysis.highLatency.length / 1000).toFixed(1);
    analysis.insights.push(`${analysis.highLatency.length} high-latency operations (avg: ${avgLatency}s)`);
  }

  return analysis;
}

function generateLessonsLearned(analysis) {
  const timestamp = new Date().toISOString().split('T')[0];
  
  let doc = `# Lessons Learned - Week of ${timestamp}\n\n`;
  doc += `**Generated by Trace Analysis Agent**\n\n`;
  doc += `## Summary\n`;
  doc += `- Total traces: ${analysis.total}\n`;
  doc += `- Success rate: ${(analysis.successful.length / analysis.total * 100).toFixed(1)}%\n`;
  doc += `- Failed traces: ${analysis.failed.length}\n\n`;

  doc += `## Insights\n`;
  for (const insight of analysis.insights) {
    doc += `- ${insight}\n`;
  }
  doc += `\n`;

  doc += `## Agent Activity\n`;
  const agentStats = Object.entries(analysis.byAgent)
    .map(([agent, count]) => ({ agent, count }))
    .sort((a, b) => b.count - a.count);
  
  for (const { agent, count } of agentStats) {
    doc += `- **${agent}**: ${count} traces\n`;
  }
  doc += `\n`;

  if (analysis.failed.length > 0) {
    doc += `## Failed Traces (Top 5)\n`;
    for (const trace of analysis.failed.slice(0, 5)) {
      const agent = trace.userId || trace.metadata?.agentId || 'unknown';
      doc += `- **${agent}**: ${trace.name} (${trace.id})\n`;
      if (trace.statusMessage) {
        doc += `  Error: ${trace.statusMessage}\n`;
      }
    }
    doc += `\n`;
  }

  if (analysis.highLatency.length > 0) {
    doc += `## High Latency Operations (>10s)\n`;
    for (const op of analysis.highLatency.slice(0, 5)) {
      doc += `- **${op.agent}**: ${(op.latency / 1000).toFixed(1)}s (${op.traceId})\n`;
    }
    doc += `\n`;
  }

  doc += `## Recommendations\n`;
  
  if (analysis.failed.length > analysis.total * 0.1) {
    doc += `- ⚠️ High failure rate (${(analysis.failed.length / analysis.total * 100).toFixed(1)}%). Review failed traces.\n`;
  }
  
  if (analysis.highLatency.length > 0) {
    doc += `- ⚠️ Latency issues detected. Optimize high-latency operations.\n`;
  }

  if (analysis.failed.length === 0 && analysis.highLatency.length === 0) {
    doc += `- ✅ No major issues detected. Keep current approach.\n`;
  }

  doc += `\n---\n*View full traces at ${LANGFUSE_BASE_URL}*\n`;

  return doc;
}

async function main() {
  console.log('Fetching traces from Langfuse...');
  const data = await fetchTraces();
  const traces = data.data || [];

  console.log(`Found ${traces.length} traces`);
  
  console.log('Analyzing patterns...');
  const analysis = await analyzeTraces(traces);

  console.log('Generating lessons learned...');
  const lessonsDoc = generateLessonsLearned(analysis);

  // Write to workspace
  const fs = require('fs');
  const outputPath = process.env.OPENCLAW_WORKSPACE + '/LESSONS_LEARNED.md';
  fs.writeFileSync(outputPath, lessonsDoc);
  
  console.log(`Written to: ${outputPath}`);
  console.log('\n' + lessonsDoc);

  return {
    tracesAnalyzed: traces.length,
    successRate: (analysis.successful.length / analysis.total * 100).toFixed(1),
    insights: analysis.insights.length
  };
}

main()
  .then(result => {
    console.log('\nAnalysis complete:', result);
    process.exit(0);
  })
  .catch(err => {
    console.error('Error:', err);
    process.exit(1);
  });
